#!/usr/bin/env bash
#I am invincible!!! when receiving a SIGTERM signal

trap highlander SIGTERM

highlander()
{
	echo "I am invincible!!!"
}
while ((8))
do
	echo "To infinity and beyond"
	sleep 2
done
